wwwdccn/chair/urls.py
from django.urls import path

from chair.views import export
from .views import dashboard, submissions, users


app_name = 'chair'

urlpatterns = [
    path('<int:conf_pk>/', dashboard.overview, name='home'),

    #
    # Submissions
    #
    path('<int:conf_pk>/submissions/', submissions.list_submissions, name='submissions'),
    path('<int:conf_pk>/submissions/create/', submissions.create_submission, name='submission-create'),
    path('<int:conf_pk>/submissions/compose_redirect/', submissions.compose_redirect, name='submissions-compose-redirect'),
    path('submissions/<int:sub_pk>/feed_item/', submissions.feed_item, name='submission-feed-item'),
    path('submissions/<int:sub_pk>/overview/', submissions.overview, name='submission-overview'),
    path('submissions/<int:sub_pk>/metadata/', submissions.metadata, name='submission-metadata'),
    path('submissions/<int:sub_pk>/authors/', submissions.authors, name='submission-authors'),
    path('submissions/<int:sub_pk>/authors/delete/', submissions.delete_author, name='submission-author-delete'),
    path('submissions/<int:sub_pk>/authors/create/', submissions.create_author, name='submission-author-create'),
    path('submissions/<int:sub_pk>/authors/invite/', submissions.invite_author, name='submission-author-invite'),
    path('submissions/<int:sub_pk>/authors/reorder/', submissions.reorder_authors, name='submission-authors-reorder'),
    path('submissions/<int:sub_pk>/rev_man/', submissions.review_manuscript, name='submission-review-manuscript'),
    path('submissions/<int:sub_pk>/rev_man/delete/', submissions.delete_review_manuscript, name='submission-review-manuscript-delete'),
    path('submissions/<int:sub_pk>/revoke_review/', submissions.revoke_review, name='revoke-review'),
    path('submissions/<int:sub_pk>/reviews/', submissions.reviews, name='submission-reviewers'),
    path('submissions/<int:sub_pk>/messages/', submissions.emails, name='submission-messages'),
    path('submissions/<int:sub_pk>/camera_ready/', submissions.camera_ready, name='submission-camera-ready'),
    path('submissions/<int:sub_pk>/reviews/assign/', submissions.assign_reviewer, name='assign-reviewer'),
    path('submissions/<int:sub_pk>/reviews/<int:rev_pk>/delete/', submissions.delete_review, name='delete-review'),
    path('submissions/<int:sub_pk>/delete/', submissions.delete_submission, name='submission-delete'),
    path('attachments/<int:att_pk>/download/', submissions.download_attachment, name='download-attachment'),

    #
    # Users
    #
    path('<int:conf_pk>/users/', users.list_users, name='users'),
    path('<int:conf_pk>/users/compose_redirect/', users.compose_redirect, name='users-compose-redirect'),
    path('<int:conf_pk>/users/<int:user_pk>/feed_item/', users.feed_item, name='user-feed-item'),
    path('<int:conf_pk>/users/<int:user_pk>/overview/', users.overview, name='user-overview'),
    path('<int:conf_pk>/users/<int:user_pk>/messages/', users.emails, name='user-messages'),
    path('<int:conf_pk>/users/export/csv/', users.export_csv, name='users-export-csv'),

    #
    # Exports
    #
    path('<int:conf_pk>/export/submissions/', export.export_submissions, name='export-submissions'),
    path('<int:conf_pk>/export/reviews_doc/', export.export_reviews_doc, name='export-reviews-doc'),
]

wwwdccn/review/urls.py
from django.urls import path

from . import views


app_name = 'review'

urlpatterns = [
    path('<int:pk>/', views.review_details, name='review-details'),
    path('<int:pk>/refuse/', views.decline_review, name='review-decline'),
    # API:
    path('api/<int:sub_id>/decision/update/', views.update_decision, name='update-decision'),
    path('api/<int:conf_pk>/users/<int:user_pk>/make_reviewer/', views.create_reviewer, name='make-reviewer'),
    path('api/<int:conf_pk>/users/<int:user_pk>/revoke_reviewer/', views.revoke_reviewer, name='revoke-reviewer'),
]

wwwdccn/submissions/urls.py
from django.urls import path

from . import views


app_name = 'submissions'


urlpatterns = [
    path('create/', views.create_submission, name='create'),
    path('create/<int:pk>/', views.create_submission_for, name='create-for'),
    path('<int:pk>/details/', views.submission_details, name='details'),
    path('<int:pk>/authors/', views.submission_authors, name='authors'),
    path('<int:pk>/manuscript/', views.edit_manuscript, name='edit-manuscript'),
    path('<int:pk>/manuscript/delete/', views.delete_manuscript, name='delete-manuscript'),
    path('<int:pk>/manuscript/download/', views.download_manuscript, name='download-manuscript'),
    path('<int:pk>', views.submission_overview, name='overview'),
    path('<int:pk>/delete/', views.submission_delete, name='delete'),
    path('<int:pk>/camera_ready/', views.camera_ready, name='camera-ready'),
    path('<int:pk>/attachments/<int:att_pk>/upload/', views.upload_attachment, name='upload-attachment'),
    path('<int:pk>/attachments/<int:att_pk>/download/', views.download_attachment, name='download-attachment'),
    path('<int:pk>/attachments/<int:att_pk>/delete/', views.delete_attachment, name='delete-attachment'),

    path('<int:pk>/authors/delete/', views.delete_author, name='delete-author'),
    path('<int:pk>/authors/create/', views.create_author, name='create-author'),
    path('<int:pk>/authors/order/', views.order_authors, name='order-authors'),
    path('<int:pk>/authors/invite/', views.send_invitation, name='invite'),

    path('<int:pk>/update_status/', views.update_status, name='update-status'),
]

wwwdccn/user_site/urls.py
from django.urls import path

from . import views


app_name = 'user_site'

urlpatterns = [
    path('submissions/', views.submissions_list, name='submissions'),
    path('reviews/', views.reviews_list, name='reviews'),
]

wwwdccn/wwwdccn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('public_site.urls')),
    path('user/', include('user_site.urls')),
    path('auth/', include('auth_app.urls')),
    path('users/', include('users.urls')),
    path('registration/', include('registration.urls')),
    path('conferences/', include('conferences.urls')),
    path('submissions/', include('submissions.urls')),
    path('chair/', include('chair.urls')),
    path('chair_mail/', include('chair_mail.urls')),
    path('review/', include('review.urls')),
    path('gears/', include('gears.urls')),
    path('proceedings/', include('proceedings.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.USE_LOCAL_MEDIA:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

wwwdccn/review/models.py
import statistics

from django.db import models
from django.db.models import Model, CharField, ForeignKey, CASCADE, SET_NULL, \
    IntegerField, FloatField, OneToOneField, ManyToManyField
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from conferences.models import Conference, ProceedingType, ProceedingVolume, \
    ArtifactDescriptor
from submissions.models import Submission
from users.models import User


class ReviewStage(Model):
    submission = models.ForeignKey(Submission, on_delete=SET_NULL, null=True)
    num_reviews_required = models.IntegerField()
    score = models.FloatField(null=True, blank=True, default=None)
    locked = models.BooleanField(default=False)

    def get_num_missing_reviews(self):
        return max(0, self.num_reviews_required - self.review_set.count())

    def update_score(self, commit=True):
        scores = [review.average_score() for review in self.review_set.all()]
        scores = [x for x in scores if x]
        prev_score = self.score
        new_score = sum(scores) / len(scores) if scores else None
        self.score = new_score
        if commit and prev_score != new_score:
            self.save()

    @property
    def decision_type(self):
        if not hasattr(self, 'decision'):
            return None
        return self.decision.decision_type


@receiver(post_save, sender=Submission)
def create_review_stage(**kwargs):
    """When submission status is UNDER_REVIEW, we create a ReviewStage for it.
    """
    submission = kwargs.get('instance')
    if (submission.status == Submission.UNDER_REVIEW and
            submission.reviewstage_set.count() == 0):
        sub_type = submission.stype
        num_reviews_required = sub_type.num_reviews if sub_type else 0
        ReviewStage.objects.create(
            submission=submission, num_reviews_required=num_reviews_required,
            locked=False)


@receiver(post_save, sender=Submission)
def update_review_stage_lock(**kwargs):
    submission = kwargs.get('instance')
    stage = submission.reviewstage_set.first()
    if submission.status in [Submission.ACCEPTED, Submission.REJECTED]:
        if stage and not stage.locked:
            stage.locked = True
            stage.save()
    elif submission.status == Submission.UNDER_REVIEW:
        if stage and stage.locked:
            stage.locked = False
            stage.save()


# Create your models here.
class Reviewer(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)


SCORE = (
    ('1', _('1 - Very Poor')),
    ('2', _('2 - Below Average')),
    ('3', _('3 - Average')),
    ('4', _('4 - Good')),
    ('5', _('5 - Excellent')),
)


class Review(models.Model):
    NUM_SCORES = 4

    # Score choices codes:
    POOR = 1
    BELOW_AVERAGE = 2
    AVERAGE = 3
    GOOD = 4
    EXCELLENT = 5

    SCORE_CHOICES = (
        (None, _('Choose your score')),
        (POOR, _('1 - Very Poor')),
        (BELOW_AVERAGE, _('2 - Below Average')),
        (AVERAGE, _('3 - Average')),
        (GOOD, _('4 - Good')),
        (EXCELLENT, _('5 - Excellent'))
    )

    reviewer = models.ForeignKey(
        Reviewer,
        on_delete=models.CASCADE,
        related_name='reviews',
    )

    stage = models.ForeignKey(
        ReviewStage, blank=True, default=None, on_delete=SET_NULL, null=True)

    locked = models.BooleanField(default=False)

    technical_merit = models.IntegerField(
        choices=SCORE_CHOICES, default=None, blank=True, null=True)
    clarity = models.IntegerField(
        choices=SCORE_CHOICES, default=None, blank=True, null=True)
    relevance = models.IntegerField(
        choices=SCORE_CHOICES, default=None, blank=True, null=True)
    originality = models.IntegerField(
        choices=SCORE_CHOICES, default=None, blank=True, null=True)

    details = models.TextField()

    submitted = models.BooleanField(default=False)

    @property
    def paper(self):
        return self.stage.submission

    def __str__(self):
        name = self.reviewer.user.profile.get_full_name()
        return f'Review for submission #{self.paper.pk} by {name}'

    def check_details(self):
        return check_review_details(self.details, self.paper.stype)

    def score_fields(self):
        return {
            'technical_merit': self.technical_merit,
            'clarity': self.clarity,
            'originality': self.originality,
            'relevance': self.relevance,
        }

    def missing_score_fields(self):
        return tuple(k for k, v in self.score_fields().items() if v is None)

    def all_scores_filled(self):
        return self.num_scores_missing() == 0

    def num_scores_missing(self):
        return len(self.missing_score_fields())

    def warnings(self):
        num_missing = self.num_scores_missing()
        warnings = []
        if num_missing == Review.NUM_SCORES and not self.details:
            warnings.append('Please, start the review')
        else:
            filled_details = self.check_details()
            filled_scores = num_missing == 0

            if not filled_scores:
                warnings.append(
                    f'{num_missing} of {Review.NUM_SCORES} scores not filled'
                )
            if not filled_details:
                warnings.append('Review details are incomplete')
            if filled_scores and filled_details and not self.submitted:
                warnings.append('Review is not submitted yet')
        return warnings

    def average_score(self):
        fields = self.score_fields()
        values = [x for x in fields.values() if x]
        return sum(values) / len(values) if values else 0


@receiver([post_save, post_delete], sender=Review)
def update_average_score_after_review_save(sender, instance, **kwargs):
    """Whenever a Review is updated or deleted, its owner should
    recompute the average score.
    """
    instance.stage.update_score(commit=True)


@receiver(post_save, sender=ReviewStage)
def update_reviews_lock(**kwargs):
    stage = kwargs.get('instance')
    updated_reviews = []
    for review in stage.review_set.all():
        if review.locked != stage.locked:
            review.locked = stage.locked
            updated_reviews.append(review)
    if updated_reviews:
        Review.objects.bulk_update(updated_reviews, ['locked'])


def check_review_details(value, submission_type):
    num_words = len(value.split())
    return num_words >= submission_type.min_num_words_in_review


class ReviewDecisionType(Model):
    ACCEPT = 'ACCEPT'
    REJECT = 'REJECT'
    CHOICES = ((ACCEPT, 'Accept submission'), (REJECT, 'Reject submission'))

    decision = CharField(choices=CHOICES, default=ACCEPT, max_length=6)
    allowed_proceedings = ManyToManyField(
        ProceedingType, related_name='decision_types')
    description = CharField(blank=True, default='', max_length=1024)
    conference = ForeignKey(Conference, on_delete=CASCADE, null=True,
                            blank=True, default=None)

    class Meta:
        unique_together = ['conference', 'decision', 'description']
        ordering = ['conference_id', 'decision', 'description']


class ReviewDecision(Model):
    decision_type = ForeignKey(
        ReviewDecisionType, on_delete=SET_NULL, related_name='decisions',
        null=True, blank=True, default=None)
    stage = OneToOneField(ReviewStage, on_delete=CASCADE,
                          related_name='decision')

    def save(self, *args, **kwargs):
        ret = super().save(*args, **kwargs)
        decision = self.decision_type.decision if self.decision_type else None
        if decision:
            submission = self.stage.submission
            if decision == ReviewDecisionType.ACCEPT:
                submission.status = Submission.ACCEPTED
                submission.save()
            elif decision == ReviewDecisionType.REJECT:
                submission.status = Submission.REJECTED
                submission.save()
        return ret


@receiver(post_save, sender=ReviewStage)
def create_decision_after_stage_created(**kwargs):
    """When ReviewStage is created, a OneToOne field ReviewDecision should
    be also created."""
    review_stage = kwargs['instance']
    if kwargs['created']:
        ReviewDecision.objects.get_or_create(stage=review_stage)


class ReviewStats(Model):
    conference = OneToOneField(Conference, on_delete=CASCADE,
                               related_name='review_stats')

    num_submissions_reviewed = IntegerField(
        default=0,
        verbose_name='Number of submissions with all reviews submitted')

    num_submissions_with_incomplete_reviews = IntegerField(
        default=0,
        verbose_name='Number of submissions with incomplete reviews')

    num_submissions_with_missing_reviewers = IntegerField(
        default=0,
        verbose_name='Number of submissions missing one or more reviewers')

    average_score = FloatField(
        default=0.0,
        verbose_name='Average score over all completely reviewed submissions')

    median_score = FloatField(
        default=0.0,
        verbose_name='Median score over all completely reviewed submissions')

    q1_score = FloatField(
        default=0.0,
        verbose_name='Q1 score (25% are not greater then)')

    q3_score = FloatField(
        default=0.0,
        verbose_name='Q3 score (25% are not less then)')

    def update_stats(self):
        """Compute and record statistics.
        """
        from review.utilities import review_finished, count_required_reviews, \
            get_average_score

        # 1) Count submissions with complete, incomplete and missing reviews
        stype_cache = {
            st.pk: st for st in self.conference.submissiontype_set.all()
        }
        submissions = self.conference.submission_set.exclude(

wwwdccn/review/templates/review/review_details.html
{% extends "user_site/base.html" %}
{% load bootstrap4 %}
{% load submission_extras %}

{% block title %}
  Review #{{ review.pk }} | DCCN
{% endblock %}

{% block header %}
  {% include 'user_site/components/navigation.html' with active='reviews' %}
{% endblock %}

{% block body %}
<main class="container py-3">
  <div class="dccn-layout-row">

      <!-- MAIN AREA -->
    <div class="dccn-panel dccn-panel-screen">
      <div class="dccn-panel-header">
        <h1 class="dccn-panel-title">Review for submission #{{ review.paper.pk }}</h1>
        <a href="{% url 'user_site:reviews' %}" class="dccn-panel-close-btn"><i class="fas fa-times fa-2x"></i></a>
      </div>

      <div class="dccn-panel-status-row">
        <p class="dccn-text-small text-muted mb-3">{{ review.paper.conference.short_name }}</p>
        <p class="dccn-text-small ml-auto mr-3" data-toggle="tooltip" title="Deadline">
          <i class="far fa-clock"></i> {{ review.paper.conference.review_stage.end_date }}
        </p>

        <div class="dccn-text-small">
          <i class="fas fa-circle {% if review.submitted %}text-success{% else %}text-warning{% endif %}"></i>
        </div>
      </div>

      {% bootstrap_messages %}

      <p class="text-center dccn-text-larger-light">{{ review.paper.title }}</p>
      <p class="text-justify dccn-text-0 mt-3"><strong>Abstract:</strong> {{ review.paper.abstract }}</p>

      <p class="dccn-text-0 mt-3"><strong>Topics:</strong></p>
      <ul class="list-unstyled mt-0">
        {% for topic in review.paper.topics.all %}
          <li class="dccn-text-0"><i class="far fa-check-square"></i> {{ topic.name }}</li>
        {% endfor %}
      </ul>

      <p class="dccn-text-0 mt-3"><strong>Submission type:</strong> {{ review.paper.stype.name }}</p>

      <p class="dccn-text-0 mt-3">
        <strong>Review Manuscript: </strong>
        <a href="{% url 'submissions:download-manuscript' pk=review.paper.pk %}" class="dccn-link" target="_blank">
          <i class="far fa-file-pdf"></i> {{ review.paper.get_review_manuscript_name }}
        </a>
      </p>

      <hr>

      <form action="" id="editForm" method="POST" novalidate>
        {% csrf_token %}
        <input type="hidden" name="submitted" value="{{ review.submitted }}" id="submittedInput">
        {% bootstrap_field edit_form.technical_merit form_group_class="form-group row" label_class="col-sm-4 col-md-3 col-lg-2" field_class="col-sm-8 col-md-9 col-lg-10" %}
        {% bootstrap_field edit_form.originality form_group_class="form-group row" label_class="col-sm-4 col-md-3 col-lg-2" field_class="col-sm-8 col-md-9 col-lg-10" %}
        {% bootstrap_field edit_form.relevance form_group_class="form-group row" label_class="col-sm-4 col-md-3 col-lg-2" field_class="col-sm-8 col-md-9 col-lg-10" %}
        {% bootstrap_field edit_form.clarity form_group_class="form-group row" label_class="col-sm-4 col-md-3 col-lg-2" field_class="col-sm-8 col-md-9 col-lg-10" %}
        {% bootstrap_field edit_form.details show_label=False placeholder="Enter detailed review here" %}
        <small class="form-text text-muted">
          <span id="detailsNumWords" data-min="{{ review.paper.stype.min_num_words_in_review }}"></span> words (min: {{ review.paper.stype.min_num_words_in_review }})
        </small>
      </form>

      <div class="dccn-text-small mt-3">
        Please fill the reviewer form. To complete the review, you need to grade technical merit,
          originality, relevance and clarity, and also provide a detailed review. The detailed review must contain at least <strong>{{ review.paper.stype.min_num_words_in_review }}</strong> words.<br>
          To finish the review, you need to press "Submit review". You can also press "Save draft" to save your current state and continue your work after a while.<br>
        Please note, that <strong>to finish the review you need to submit it</strong>. The review status at the top right corner then becomes green.<br>
        You can also refuse to review at any time, just press the button "Refuse to review this paper" and confirm your refuse.
      </div>

      <div class="d-flex my-3">
        {% if not review.submitted %}
          <button type="submit" class="btn btn-primary" form="editForm" id="submitReviewBtn">Submit review</button>
          <button type="submit" class="btn btn-outline-secondary ml-2" form="editForm">Save draft</button>
        {% else %}
          <button class="btn btn-primary" form="editForm">Save</button>
        {% endif %}
        <button type="button" class="btn btn-danger ml-auto" data-toggle="modal" data-target="#declineReviewModal">Refuse to review this paper</button>
      </div>

      <div class="modal" tabindex="-1" role="dialog" id="declineReviewModal">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Decline the review</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to refuse to review this paper? All changes you made to the review will be lost and you will not have access to the paper anymore.</p>
            </div>
            <div class="modal-footer">
              <form action="{% url 'review:review-decline' pk=review.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Confirm</button>
              </form>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

{% block script %}
<script>
$(document).ready(function () {
  const detailsInput = $('#id_details');
  const numWordsSpan = $('#detailsNumWords');
  const minNumWords = parseInt(numWordsSpan.attr('data-min'));

  function countWords(s) {
    const words = s.trim().split(/\s+/);
    if (words.length === 1 && words[0] === "") {
      return 0;
    }
    return words.length;
  }

  function fillNumWordsSpan() {
    const numWords = countWords(detailsInput.val());
    const cname = (numWords >= minNumWords) ? 'text-success' : 'text-danger';
    numWordsSpan.html(`<span class="${cname}">${numWords}</span>`);
  }

  $('#submitReviewBtn').on('click', function () {
    $('#submittedInput').val('True');
  });
  detailsInput.on('input', fillNumWordsSpan);

  // Fill num words for the first time:
  fillNumWordsSpan();
});
</script>
{% endblock %}