wwwdccn/chair/urls.py
from django.urls import path

from chair.views import export
from .views import dashboard, submissions, users


app_name = 'chair'

urlpatterns = [
    path('<int:conf_pk>/', dashboard.overview, name='home'),

    #
    # Submissions
    #
    path('<int:conf_pk>/submissions/', submissions.list_submissions, name='submissions'),
    path('<int:conf_pk>/submissions/create/', submissions.create_submission, name='submission-create'),
    path('<int:conf_pk>/submissions/compose_redirect/', submissions.compose_redirect, name='submissions-compose-redirect'),
    path('submissions/<int:sub_pk>/feed_item/', submissions.feed_item, name='submission-feed-item'),
    path('submissions/<int:sub_pk>/overview/', submissions.overview, name='submission-overview'),
    path('submissions/<int:sub_pk>/metadata/', submissions.metadata, name='submission-metadata'),
    path('submissions/<int:sub_pk>/authors/', submissions.authors, name='submission-authors'),
    path('submissions/<int:sub_pk>/authors/delete/', submissions.delete_author, name='submission-author-delete'),
    path('submissions/<int:sub_pk>/authors/create/', submissions.create_author, name='submission-author-create'),
    path('submissions/<int:sub_pk>/authors/invite/', submissions.invite_author, name='submission-author-invite'),
    path('submissions/<int:sub_pk>/authors/reorder/', submissions.reorder_authors, name='submission-authors-reorder'),
    path('submissions/<int:sub_pk>/rev_man/', submissions.review_manuscript, name='submission-review-manuscript'),
    path('submissions/<int:sub_pk>/rev_man/delete/', submissions.delete_review_manuscript, name='submission-review-manuscript-delete'),
    path('submissions/<int:sub_pk>/revoke_review/', submissions.revoke_review, name='revoke-review'),
    path('submissions/<int:sub_pk>/reviews/', submissions.reviews, name='submission-reviewers'),
    path('submissions/<int:sub_pk>/messages/', submissions.emails, name='submission-messages'),
    path('submissions/<int:sub_pk>/camera_ready/', submissions.camera_ready, name='submission-camera-ready'),
    path('submissions/<int:sub_pk>/reviews/assign/', submissions.assign_reviewer, name='assign-reviewer'),
    path('submissions/<int:sub_pk>/reviews/<int:rev_pk>/delete/', submissions.delete_review, name='delete-review'),
    path('submissions/<int:sub_pk>/delete/', submissions.delete_submission, name='submission-delete'),
    path('attachments/<int:att_pk>/download/', submissions.download_attachment, name='download-attachment'),

    #
    # Users
    #
    path('<int:conf_pk>/users/', users.list_users, name='users'),
    path('<int:conf_pk>/users/compose_redirect/', users.compose_redirect, name='users-compose-redirect'),
    path('<int:conf_pk>/users/<int:user_pk>/feed_item/', users.feed_item, name='user-feed-item'),
    path('<int:conf_pk>/users/<int:user_pk>/overview/', users.overview, name='user-overview'),
    path('<int:conf_pk>/users/<int:user_pk>/messages/', users.emails, name='user-messages'),
    path('<int:conf_pk>/users/export/csv/', users.export_csv, name='users-export-csv'),

    #
    # Exports
    #
    path('<int:conf_pk>/export/submissions/', export.export_submissions, name='export-submissions'),
    path('<int:conf_pk>/export/reviews_doc/', export.export_reviews_doc, name='export-reviews-doc'),
]

wwwdccn/chair_mail/urls.py
from django.urls import path

from chair_mail import forms
from chair_mail.models import MSG_TYPE_USER, MSG_TYPE_SUBMISSION
from . import views, api


app_name = 'chair_mail'

urlpatterns = [
    path('<int:conf_pk>/overview/', views.overview, name='overview'),
    path('<int:conf_pk>/frame/', views.frame_details, name='frame-details'),
    path('<int:conf_pk>/frame/create/',
         views.create_frame,
         name='create-frame'),
    path('<int:conf_pk>/frame/send_test_message/',
         views.send_frame_test_message,
         name='send-frame-test'),
    path('<int:conf_pk>/frame/preview/',
         views.render_frame_preview,
         name='render-frame-preview'),
    path('<int:conf_pk>/messages/',
         views.sent_messages,
         name='sent-messages'),
    path('<int:conf_pk>/messages/<int:msg_pk>/',
         views.group_message_details,
         name='message-details'),
    path('<int:conf_pk>/messages/instance/<int:msg_pk>/',
         views.message_details,
         name='instance-details'),
    path('<int:conf_pk>/messages/delete/',
         views.delete_all_messages,
         name='delete-all-messages'),
    path('<int:conf_pk>/compose/user/',
         views.create_compose_view(MSG_TYPE_USER, 'fas fa-user'),
         name='compose-user'),
    path('<int:conf_pk>/compose/submission/',
         views.create_compose_view(MSG_TYPE_SUBMISSION, 'fas fa-scroll'),
         name='compose-submission'),
    path('help/compose/', views.help_compose, name='help-compose'),

    # Notifications:
    path('<int:conf_pk>/notifications/', views.notifications_list,
         name='notifications'),
    path('<int:conf_pk>/notifications/<int:notif_pk>/',
         views.notification_details, name='notification-details'),
    path('<int:conf_pk>/notifications/reset/', views.reset_all_notifications,
         name='reset-notifications'),
    path('<int:conf_pk>/notifications/refresh/', views.refresh_notifications,
         name='refresh-notifications'),
    path('<int:conf_pk>/notifications/<int:notif_pk>/reset/',
         views.reset_notification, name='reset-notification'),
    path('<int:conf_pk>/notifications/<int:notif_pk>/update_state/',
         views.update_notification_state, name='update-notification-state'),

    #########################################################################
    path('<int:conf_pk>/api/mailing_lists/', api.list_mailing_lists,
         name='list-mailing-lists'),
    path('<int:conf_pk>/api/mailing_lists/<str:name>/',
         api.mailing_list_details, name='mailing-list-details'),
    path('<int:conf_pk>/api/users/', api.list_users, name='list-users'),
    path('<int:conf_pk>/api/submissions/', api.list_submissions,
         name='list-submissions'),
    path('<int:conf_pk>/api/preview/user/',
         api.create_preview_view(forms.PreviewUserMessageForm),
         name='render-preview-user'),
    path('<int:conf_pk>/api/preview/submission/',
         api.create_preview_view(forms.PreviewSubmissionMessageForm),
         name='render-preview-submission'),
]

wwwdccn/submissions/urls.py
from django.urls import path

from . import views


app_name = 'submissions'


urlpatterns = [
    path('create/', views.create_submission, name='create'),
    path('create/<int:pk>/', views.create_submission_for, name='create-for'),
    path('<int:pk>/details/', views.submission_details, name='details'),
    path('<int:pk>/authors/', views.submission_authors, name='authors'),
    path('<int:pk>/manuscript/', views.edit_manuscript, name='edit-manuscript'),
    path('<int:pk>/manuscript/delete/', views.delete_manuscript, name='delete-manuscript'),
    path('<int:pk>/manuscript/download/', views.download_manuscript, name='download-manuscript'),
    path('<int:pk>', views.submission_overview, name='overview'),
    path('<int:pk>/delete/', views.submission_delete, name='delete'),
    path('<int:pk>/camera_ready/', views.camera_ready, name='camera-ready'),
    path('<int:pk>/attachments/<int:att_pk>/upload/', views.upload_attachment, name='upload-attachment'),
    path('<int:pk>/attachments/<int:att_pk>/download/', views.download_attachment, name='download-attachment'),
    path('<int:pk>/attachments/<int:att_pk>/delete/', views.delete_attachment, name='delete-attachment'),

    path('<int:pk>/authors/delete/', views.delete_author, name='delete-author'),
    path('<int:pk>/authors/create/', views.create_author, name='create-author'),
    path('<int:pk>/authors/order/', views.order_authors, name='order-authors'),
    path('<int:pk>/authors/invite/', views.send_invitation, name='invite'),

    path('<int:pk>/update_status/', views.update_status, name='update-status'),
]

wwwdccn/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('search/', views.search_users, name='search'),
    path('profile/overview/', views.profile_overview, name='profile-overview'),
    path('profile/account/', views.profile_account, name='profile-account'),
    path('profile/personal/', views.profile_personal, name='profile-personal'),
    path('profile/professional/', views.profile_professional,
         name='profile-professional'),
    path('profile/reviewer/', views.profile_reviewer, name='profile-reviewer'),
    path('email/update/', views.update_email, name='update-email'),
    path('subscriptions/update/', views.update_subscriptions,
         name='update-subscriptions'),
    path('password/update/', views.update_password, name='update-password'),
    path('avatar/update/', views.update_avatar, name='update-avatar'),
    path('avatar/delete/', views.delete_avatar, name='delete-avatar'),
    path('delete/', views.delete_account, name='delete'),
]

wwwdccn/wwwdccn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('public_site.urls')),
    path('user/', include('user_site.urls')),
    path('auth/', include('auth_app.urls')),
    path('users/', include('users.urls')),
    path('registration/', include('registration.urls')),
    path('conferences/', include('conferences.urls')),
    path('submissions/', include('submissions.urls')),
    path('chair/', include('chair.urls')),
    path('chair_mail/', include('chair_mail.urls')),
    path('review/', include('review.urls')),
    path('gears/', include('gears.urls')),
    path('proceedings/', include('proceedings.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.USE_LOCAL_MEDIA:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

wwwdccn/chair/models.py
from django.db import models

# Create your models here.

wwwdccn/chair/views/dashboard.py
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_GET

from conferences.utilities import validate_chair_access
from conferences.models import Conference
from submissions.models import Submission
from users.models import User


@require_GET
def overview(request, conf_pk):
    conference = get_object_or_404(Conference, pk=conf_pk)
    validate_chair_access(request.user, conference)

    submission_types = tuple({
        'length': st.submissions.count(),
        'name': st.name.capitalize(),
    } for st in conference.submissiontype_set.all())

    num_submissions = Submission.objects.filter(stype__isnull=False).count()

    num_authors = User.objects.filter(
        authorship__submission__conference__pk=conf_pk
    ).count()

    return render(request, 'chair/dashboard/dashboard.html', context={
        'conference': conference,
        'num_submissions': num_submissions,
        'num_authors': num_authors,
    })

wwwdccn/user_site/views/submissions.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from submissions.models import Submission


@login_required
def user_details(request):
    return render(request, 'user_site/submissions.html', {
        'submissions': Submission.objects.filter(authors__user=request.user)
    })

wwwdccn/chair/templates/chair/submissions/_tab_nav.html
{###########################################################################}
{# Tab navigation for submission details.                                  #}
{#                                                                         #}
{# CONTEXT:                                                                #}
{# - `submission`                                                          #}
{# - `active`: a string indicating which tab is currently active.          #}
{###########################################################################}
{% load review_extras %}
<ul class="nav nav-pills justify-content-start">
  <li class="nav-item">
    <a href="{% url 'chair:submission-overview' sub_pk=submission.pk %}"
       class="nav-link {% if active == 'overview' %}active{% endif %}">
      Overview
    </a>
  </li>
  <li class="nav-item">
    <a href="{% url 'chair:submission-metadata' sub_pk=submission.pk %}"
       class="nav-link {% if active == 'metadata' %}active{% endif %}">
      Metadata
    </a>
  </li>
  <li class="nav-item">
    <a href="{% url 'chair:submission-authors' sub_pk=submission.pk %}"
       class="nav-link {% if active == 'authors' %}active{% endif %}">
      Authors
    </a>
  </li>
  <li class="nav-item">
    <a href="{% url 'chair:submission-review-manuscript' sub_pk=submission.pk %}"
       class="nav-link {% if active == 'review-manuscript' %}active{% endif %}">
      Review Manuscript
    </a>
  </li>
  <li class="nav-item">
    {% with stage=submission|review_stage_of %}
    <a href="{% url 'chair:submission-reviewers' sub_pk=submission.pk %}"
       class="nav-link {% if active == 'reviews' %}active{% endif %} {% if submission.status == 'SUBMIT' %}disabled text-dark-2{% endif %}">
      Reviews {% if submission.status != 'SUBMIT' %}({{ stage.review_set.count }}/{{ stage.num_reviews_required }}){% endif %}
    </a>
    {% endwith %}
  </li>
  <li class="nav-item">
    <a href="{% url 'chair:submission-messages' sub_pk=submission.pk %}"
       class="nav-link {% if active == 'messages' %}active{% endif %}">
      Messages
    </a>
  </li>
  <li class="nav-item">
    <a href="{% url 'chair:submission-camera-ready' sub_pk=submission.pk %}"
       class="nav-link {% if active == 'camera-ready' %}active{% endif %}">
      Camera-ready
    </a>
  </li>
</ul>

wwwdccn/chair/templates/chair/submissions/list.html
{###########################################################################}
{# Submissions list paged view.                                            #}
{#                                                                         #}
{# CONTEXT:                                                                #}
{# - `filter_form`: a submissions filter form                              #}
{#                                                                         #}
{# INHERITED CONTEXT:                                                      #}
{# - `page`: a `Page` object, items passed inside is an iterable of PKs    #}
{# - `list_view_url`: this list view URL without query-string part.        #}
{# - `conference`: conference identifier                                   #}
{###########################################################################}
{% extends 'chair/base/list_page.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extrahead %}
  {{ filter_form.media }}
  <script src="{% static 'gears/js/dropdown_select_submit.js' %}"></script>
{% endblock %}

{#---------------------------------------------------------------------------#}
{# Navigation and breadcrumbs                                                #}
{#---------------------------------------------------------------------------#}
{% block navigation %}
  {% include 'chair/components/navigation.html' with active='submissions' %}
{% endblock %}

{% block smallScreenBreadcrumbItems %}
  <li class="breadcrumb-item active">submissions</li>
{% endblock %}

{% block largeScreenBreadcrumbItems %}
  <li class="breadcrumb-item active">submissions</li>
{% endblock %}

{% block toolbar %}
  <form action="{% url 'chair:submissions' conf_pk=conference.pk %}" method="GET" class="m-2" id="filterForm">
    <input type="hidden" name="next" value="{{ request.get_full_path }}">
  </form>

  <div class="d-flex mb-3">
    {% render_field filter_form.term class+="form-control form-control-sm" bound_css_class='' placeholder="Search by title, authors or ID" type="search" form="filterForm" %}
    <button type="submit" form="filterForm" class="btn btn-sm btn-outline-secondary ml-1" id="searchBtn">
      <i class="fas fa-search"></i>
    </button>
  </div>

  <div class="container-fluid px-0 border-bottom">
    <div class="row mb-3">
      <div class="col-sm-3 col-12">
        <div class="btn-group btn-group-sm">
          <form action="{% url 'chair:submission-create' conf_pk=conference.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-success"><i class="fas fa-plus"></i></button>
          </form>
          {# Export #}
          <div class="dropdown">
            <a href="#" data-toggle="dropdown" class="btn btn-sm btn-secondary ml-1">
              <i class="fas fa-download"></i>
            </a>
            <div class="dropdown-menu">
              <a href="{% url 'chair:export-submissions' conf_pk=conference.pk %}?next={{ request.get_full_path|urlencode }}" class="dropdown-item">
                <i class="far fa-file-excel mr-2"></i> Export to CSV
              </a>
              <a href="{% url 'chair:export-reviews-doc' conf_pk=conference.pk %}?next={{ request.get_full_path|urlencode }}" class="dropdown-item">
                <i class="far fa-file-word mr-2"></i> Export reviews to DOC
              </a>
            </div>
          </div>
          <button type="submit" class="btn btn-primary ml-1" form="filterForm"
                  formaction="{% url 'chair:submissions-compose-redirect' conf_pk=conference.pk%}">
            <i class="far fa-paper-plane"></i>
          </button>
        </div>
      </div>

      <div class="col-sm-9 col-12">
        <div class="d-flex mt-3 mt-sm-0 align-items-center">
          <div class="ml-auto">
            {% render_field filter_form.order class+="form-control form-control-sm active-form-control" form="filterForm" %}
          </div>
          <div class="ml-1">
            {% render_field filter_form.direction class+="form-control form-control-sm active-form-control" form="filterForm" %}
          </div>
          <a href="{% url 'chair:submissions' conf_pk=conference.pk %}" class="btn btn-link dccn-link dccn-text-small ml-3">Clear filter</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}



{#---------------------------------------------------------------------------#}
{# List view content                                                         #}
{#---------------------------------------------------------------------------#}
{% block listViewContent %}
  {% for item in page %}
    <div class="dccn-feed-item pb-3"
         data-html-src="{% url 'chair:submission-feed-item' sub_pk=item %}"
         data-list-view-url="{{ request.get_full_path }}">
      <div class="d-flex"><div class="mx-auto text-center"><div class="spinner-border"></div><p>Loading</p></div></div>
    </div>
  {% endfor %}
{% endblock %}



{#---------------------------------------------------------------------------#}
{# Filter                                                                    #}
{#---------------------------------------------------------------------------#}
{% block filter %}
  <div class="dccn-chair-workspace-filter p-3" id="filterPanel">
    {% render_field filter_form.completion form="filterForm" %}
    {% render_field filter_form.types form="filterForm" %}
    {% render_field filter_form.topics form="filterForm" %}
    {% render_field filter_form.status form="filterForm" %}
    {% render_field filter_form.proc_types form="filterForm" %}
    {% render_field filter_form.volumes form="filterForm" %}
    {% render_field filter_form.quartiles form="filterForm" %}
    {% render_field filter_form.countries form="filterForm" %}
    {% render_field filter_form.affiliations form="filterForm" %}
    {% render_field filter_form.artifacts form='filterForm' %}
  </div>
{% endblock %}



{#---------------------------------------------------------------------------#}
{# Script                                                                    #}
{#---------------------------------------------------------------------------#}
{% block listPageScript %}
<script src="{% static 'chair/js/submission-actions.js' %}"></script>
<script>
$(document).ready(() => {
  $('[data-html-src]').each(function () {
    const div = $(this);
    const url = div.attr('data-html-src');
    const params = {'list_view_url': div.attr('data-list-view-url')};
    $.get(url, params, data => {
      div.html(data);
    });
  });

  $('.active-form-control').on('change', function () {
    const el = $(this);
    let form = el.parents('form');
    if (form.length === 0) {
      form = $(`#${el.attr('form')}`);
    }
    form.submit();
  });

  $('input[type="search"]').keypress(function (e) {
    if (e.keyCode === 13) {
      $('#searchBtn').click();
      return false;
    }
  });
});
</script>
{% endblock %}

wwwdccn/chair/templates/chair/submissions/submission_authors.html
{###########################################################################}
{# View and edit submission authors.                                       #}
{#                                                                         #}
{# CONTEXT:                                                                #}
{# - `authors`: a list of records with the following fields:               #}
{#   * `pk`: ID of the author                                              #}
{#   * `full_name`: full name in English                                   #}
{#   * `affiliation`:  author affiliation                                  #}
{#   * `avatar_url`: URL of the corresponding profile avatar               #}
{#   * `is_creator`: this author is the creator of the submission          #}
{#                                                                         #}
{# INHERITED CONTEXT:                                                      #}
{# - `conference`                                                          #}
{# - `submission`                                                          #}
{# - `active_tab`                                                          #}
{###########################################################################}
{% extends 'chair/submissions/_base.html' %}
{% load gears_extras %}
{% load submission_extras %}
{% load bootstrap4 %}

{% block tabViewContent %}
  <div class="dccn-authors-editor dccn-reorder" id="authorsEditor">
    <ul class="dccn-authors-editor-list dccn-reorder-list" id="authorsList">
    {% for author in submission.authors.all %}
      {% with profile=author.user.profile %}
        <li class="dccn-authors-editor-author dccn-reorder-list-item" data-id="{{ author.pk }}">
          <img src="{{ profile.avatar.url }}" alt="{{ profile.get_full_name }} profile image" class="rounded-circle">
          <div>
            <h4 class="dccn-text-3-light">{{ profile.get_full_name }}</h4>
            <p class="dccn-text-small text-muted">{{ profile.affiliation }}</p>
          </div>

          {% if profile.user != submission.created_by %}
            <!-- Delete author modal toggle: -->
            <button class="btn btn-link dccn-link ml-auto" data-toggle="modal"  data-target="#delAuthor-{{ author.pk }}">
              <i class="fas fa-times-circle"></i> Delete
            </button>

            <!-- Delete author modal dialog: -->
            <div class="modal fade" id="delAuthor-{{ author.pk }}">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header bg-danger text-light">
                    <h5 class="modal-title">Confirm delete author</h5>
                    <button class="close" data-dismiss="modal">
                      <span>&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <p class="dccn-text-0-light">
                      Are you sure you want to delete {{ profile.get_full_name }} from the co-authors list?
                    </p>
                    <form action="{% url 'chair:submission-author-delete' sub_pk=submission.pk %}"
                          method="POST">
                      {% csrf_token %}
                      <input type="hidden" name="author_pk" value="{{ author.pk }}">
                      <div class="form-row">
                        <div class="mx-auto">
                          <input type="submit" value="Delete" class="btn btn-danger btn-lg">
                          <button class="btn btn-outline-secondary btn-lg" data-dismiss="modal">
                            Cancel
                          </button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- End of modal dialog -->
          {% endif %}

        </li>
      {% endwith %}
    {% endfor %}
    </ul>

    <form action="{% url 'chair:submission-authors-reorder' sub_pk=submission.pk %}"
          method="POST" class="dccn-reorder-form" novalidate>
      {% csrf_token %}
      <input type="hidden" name="pks" class="dccn-reorder-form-input">
    </form>
  </div>

  <div class="dccn-authors-search" id="addNewAuthor" data-source="{% url 'users:search' %}">
    <div class="dccn-authors-search-content">
      <form class="dccn-authors-search-form d-flex">
        <input type="search" name="q" id="searchInput" class="form-control form-control-lg flex-fill mr-1"
               placeholder="Start typing">
        <button type="button" name="button" class="dccn-action-hide btn btn-link btn-lg px-2">
          <i class="fas fa-times"></i>
        </button>
      </form>
      <div class="dccn-authors-search-preview">
        <div class="dccn-placeholder active">
          <h4 class="h3 text-center mt-2">No authors found</h4>
          <p class="mt-3 dccn-text-small-light text-muted text-center">
            Only registered users can be added as authors.
            If you can not find your co-author in our database, then, perhaps, he or she hasn't
            registered yet. You can send an invitation, and come back here after your co-author
            finishes registration.
          </p>
          <div class="row mt-3">
            <button class="btn btn-link dccn-link mx-auto" data-toggle="modal"
                    data-target="#inviteUserDialog">
              <i class="fas fa-plus-circle"></i> Invite user
            </button>
          </div>
        </div>
        <div class="dccn-content">
        </div>
      </div>

      <form action="{% url 'chair:submission-author-create' sub_pk=submission.pk %}" method="POST"
            class="dccn-hidden-form" novalidate>
        {% csrf_token %}
        <input type="hidden" name="user_pk" id="user_pk">
      </form>

    </div>

    <button class="btn btn-link dccn-link dccn-action-show">
      <i class="fas fa-plus-circle"></i> Add co-author
    </button>
  </div>

  <div class="modal fade" id="inviteUserDialog">
    <div class="modal-dialog modal-dialog-centered modal-xl">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Invite new author</h5>
          <button class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{% url 'chair:submission-author-invite' sub_pk=submission.pk %}"
                method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="email">Enter user email:</label>
              <input type="email" name="email" class="form-control form-control-lg"
                     placeholder="user@example.com">
            </div>
            <div class="form-row form-group">
              <div class="col-md-6">
                <label for="first_name">First name (in English):</label>
                <input type="text" name="first_name" class="form-control form-control-lg" id="first_name">
              </div>
              <div class="col-md-6">
                <label for="last_name">Last name (in English):</label>
                <input type="text" name="last_name" class="form-control form-control-lg" id="last_name">
              </div>
            </div>
            <div class="form-row mt-4">
              <div class="mx-auto">
                <button type="submit" class="btn btn-success btn-lg">Invite</button>
                <button class="btn btn-outline-secondary btn-lg" data-dismiss="modal">Cancel</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
{% endblock %}

wwwdccn/chair/templates/chair/submissions/submission_review_manuscript.html
{###########################################################################}
{# View, update or delete review manuscript.                               #}
{#                                                                         #}
{# CONTEXT:                                                                #}
{# - `form`: form with 'review_manuscript' field                           #}
{#                                                                         #}
{# INHERITED CONTEXT:                                                      #}
{# - `conference`                                                          #}
{# - `submission`                                                          #}
{# - `active_tab`                                                          #}
{###########################################################################}
{% extends 'chair/submissions/_base.html' %}
{% load bootstrap4 %}

{% block tabViewContent %}
  <div class="dccn-file-vd">
    <form action="{% url 'chair:submission-review-manuscript-delete' sub_pk=submission.pk %}"
          method="POST" id="deleteManuscriptForm">
      {% csrf_token %}
    </form>
    <div class="dccn-file-vd-box">
      {% if submission.review_manuscript %}
        <p class="my-1">Current document:
          <a href="{% url 'submissions:download-manuscript' pk=submission.pk %}" target="_blank">
            <i class="far fa-file-pdf"></i> {{ submission.get_review_manuscript_name }}
          </a>
        </p>
      {% endif %}
    </div>
  </div>

  <form method="POST" action="{% url 'chair:submission-review-manuscript' sub_pk=submission.pk %}"
        class="mt-3" enctype="multipart/form-data" id="uploadForm" novalidate>
    {% csrf_token %}
    {% bootstrap_form_errors form type='non_fields' %}
    {% bootstrap_field form.review_manuscript %}
  </form>

  <div class="d-flex mt-4">
    <button type="submit" class="btn btn-outline-primary" form="uploadForm">
      Upload <i class="fas fa-save"></i>
    </button>
    <button type="submit" class="btn btn-danger ml-3" form="deleteManuscriptForm"
            {% if not submission.review_manuscript %}disabled{% endif %}>
      <i class="far fa-trash-alt"></i> Delete
    </button>
  </div>
{% endblock %}