wwwdccn/chair/urls.py
from django.urls import path

from chair.views import export
from .views import dashboard, submissions, users


app_name = 'chair'

urlpatterns = [
    path('<int:conf_pk>/', dashboard.overview, name='home'),

    #
    # Submissions
    #
    path('<int:conf_pk>/submissions/', submissions.list_submissions, name='submissions'),
    path('<int:conf_pk>/submissions/create/', submissions.create_submission, name='submission-create'),
    path('<int:conf_pk>/submissions/compose_redirect/', submissions.compose_redirect, name='submissions-compose-redirect'),
    path('submissions/<int:sub_pk>/feed_item/', submissions.feed_item, name='submission-feed-item'),
    path('submissions/<int:sub_pk>/overview/', submissions.overview, name='submission-overview'),
    path('submissions/<int:sub_pk>/metadata/', submissions.metadata, name='submission-metadata'),
    path('submissions/<int:sub_pk>/authors/', submissions.authors, name='submission-authors'),
    path('submissions/<int:sub_pk>/authors/delete/', submissions.delete_author, name='submission-author-delete'),
    path('submissions/<int:sub_pk>/authors/create/', submissions.create_author, name='submission-author-create'),
    path('submissions/<int:sub_pk>/authors/invite/', submissions.invite_author, name='submission-author-invite'),
    path('submissions/<int:sub_pk>/authors/reorder/', submissions.reorder_authors, name='submission-authors-reorder'),
    path('submissions/<int:sub_pk>/rev_man/', submissions.review_manuscript, name='submission-review-manuscript'),
    path('submissions/<int:sub_pk>/rev_man/delete/', submissions.delete_review_manuscript, name='submission-review-manuscript-delete'),
    path('submissions/<int:sub_pk>/revoke_review/', submissions.revoke_review, name='revoke-review'),
    path('submissions/<int:sub_pk>/reviews/', submissions.reviews, name='submission-reviewers'),
    path('submissions/<int:sub_pk>/messages/', submissions.emails, name='submission-messages'),
    path('submissions/<int:sub_pk>/camera_ready/', submissions.camera_ready, name='submission-camera-ready'),
    path('submissions/<int:sub_pk>/reviews/assign/', submissions.assign_reviewer, name='assign-reviewer'),
    path('submissions/<int:sub_pk>/reviews/<int:rev_pk>/delete/', submissions.delete_review, name='delete-review'),
    path('submissions/<int:sub_pk>/delete/', submissions.delete_submission, name='submission-delete'),
    path('attachments/<int:att_pk>/download/', submissions.download_attachment, name='download-attachment'),

    #
    # Users
    #
    path('<int:conf_pk>/users/', users.list_users, name='users'),
    path('<int:conf_pk>/users/compose_redirect/', users.compose_redirect, name='users-compose-redirect'),
    path('<int:conf_pk>/users/<int:user_pk>/feed_item/', users.feed_item, name='user-feed-item'),
    path('<int:conf_pk>/users/<int:user_pk>/overview/', users.overview, name='user-overview'),
    path('<int:conf_pk>/users/<int:user_pk>/messages/', users.emails, name='user-messages'),
    path('<int:conf_pk>/users/export/csv/', users.export_csv, name='users-export-csv'),

    #
    # Exports
    #
    path('<int:conf_pk>/export/submissions/', export.export_submissions, name='export-submissions'),
    path('<int:conf_pk>/export/reviews_doc/', export.export_reviews_doc, name='export-reviews-doc'),
]

wwwdccn/chair_mail/urls.py
from django.urls import path

from chair_mail import forms
from chair_mail.models import MSG_TYPE_USER, MSG_TYPE_SUBMISSION
from . import views, api


app_name = 'chair_mail'

urlpatterns = [
    path('<int:conf_pk>/overview/', views.overview, name='overview'),
    path('<int:conf_pk>/frame/', views.frame_details, name='frame-details'),
    path('<int:conf_pk>/frame/create/',
         views.create_frame,
         name='create-frame'),
    path('<int:conf_pk>/frame/send_test_message/',
         views.send_frame_test_message,
         name='send-frame-test'),
    path('<int:conf_pk>/frame/preview/',
         views.render_frame_preview,
         name='render-frame-preview'),
    path('<int:conf_pk>/messages/',
         views.sent_messages,
         name='sent-messages'),
    path('<int:conf_pk>/messages/<int:msg_pk>/',
         views.group_message_details,
         name='message-details'),
    path('<int:conf_pk>/messages/instance/<int:msg_pk>/',
         views.message_details,
         name='instance-details'),
    path('<int:conf_pk>/messages/delete/',
         views.delete_all_messages,
         name='delete-all-messages'),
    path('<int:conf_pk>/compose/user/',
         views.create_compose_view(MSG_TYPE_USER, 'fas fa-user'),
         name='compose-user'),
    path('<int:conf_pk>/compose/submission/',
         views.create_compose_view(MSG_TYPE_SUBMISSION, 'fas fa-scroll'),
         name='compose-submission'),
    path('help/compose/', views.help_compose, name='help-compose'),

    # Notifications:
    path('<int:conf_pk>/notifications/', views.notifications_list,
         name='notifications'),
    path('<int:conf_pk>/notifications/<int:notif_pk>/',
         views.notification_details, name='notification-details'),
    path('<int:conf_pk>/notifications/reset/', views.reset_all_notifications,
         name='reset-notifications'),
    path('<int:conf_pk>/notifications/refresh/', views.refresh_notifications,
         name='refresh-notifications'),
    path('<int:conf_pk>/notifications/<int:notif_pk>/reset/',
         views.reset_notification, name='reset-notification'),
    path('<int:conf_pk>/notifications/<int:notif_pk>/update_state/',
         views.update_notification_state, name='update-notification-state'),

    #########################################################################
    path('<int:conf_pk>/api/mailing_lists/', api.list_mailing_lists,
         name='list-mailing-lists'),
    path('<int:conf_pk>/api/mailing_lists/<str:name>/',
         api.mailing_list_details, name='mailing-list-details'),
    path('<int:conf_pk>/api/users/', api.list_users, name='list-users'),
    path('<int:conf_pk>/api/submissions/', api.list_submissions,
         name='list-submissions'),
    path('<int:conf_pk>/api/preview/user/',
         api.create_preview_view(forms.PreviewUserMessageForm),
         name='render-preview-user'),
    path('<int:conf_pk>/api/preview/submission/',
         api.create_preview_view(forms.PreviewSubmissionMessageForm),
         name='render-preview-submission'),
]

wwwdccn/wwwdccn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('public_site.urls')),
    path('user/', include('user_site.urls')),
    path('auth/', include('auth_app.urls')),
    path('users/', include('users.urls')),
    path('registration/', include('registration.urls')),
    path('conferences/', include('conferences.urls')),
    path('submissions/', include('submissions.urls')),
    path('chair/', include('chair.urls')),
    path('chair_mail/', include('chair_mail.urls')),
    path('review/', include('review.urls')),
    path('gears/', include('gears.urls')),
    path('proceedings/', include('proceedings.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.USE_LOCAL_MEDIA:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

wwwdccn/chair_mail/models.py
from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.db.models import ForeignKey, OneToOneField, TextField, CharField, \
    SET_NULL, CASCADE, BooleanField, UniqueConstraint
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template import Template, Context
from django.utils import timezone
from markdown import markdown
from html2text import html2text

from chair_mail.context import get_conference_context, get_user_context, \
    get_submission_context, get_frame_context
from conferences.models import Conference
from submissions.models import Submission
from users.models import User

MSG_TYPE_USER = 'user'
MSG_TYPE_SUBMISSION = 'submission'

MESSAGE_TYPE_CHOICES = (
    (MSG_TYPE_USER, 'Message to users'),
    (MSG_TYPE_SUBMISSION, 'Message to submissions'),
)


class EmailFrame(models.Model):
    text_html = models.TextField()
    text_plain = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)

    @staticmethod
    def render(frame_template, conference, subject, body):
        context_data = get_frame_context(conference, subject, body)
        context = Context(context_data, autoescape=False)
        return Template(frame_template).render(context)

    def render_html(self, subject, body):
        return EmailFrame.render(
            self.text_html, self.conference, subject, body
        )

    def render_plain(self, subject, body):
        text_plain = self.text_plain
        if not text_plain:
            text_plain = html2text(self.text_html)
        return EmailFrame.render(
            text_plain, self.conference, subject, body
        )


class EmailSettings(models.Model):
    frame = models.ForeignKey(EmailFrame, on_delete=models.SET_NULL, null=True)
    conference = models.OneToOneField(
        Conference, null=True, blank=True, on_delete=models.CASCADE,
        related_name='email_settings',
    )


class GroupMessage(models.Model):
    subject = models.CharField(max_length=1024)
    body = models.TextField()
    conference = models.ForeignKey(
        Conference,
        on_delete=models.CASCADE,
        related_name='sent_group_emails',
    )
    sent_at = models.DateTimeField(auto_now_add=True)
    sent_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True,
        related_name='sent_group_emails'
    )
    sent = models.BooleanField(default=False)

    @property
    def message_type(self):
        return ''


class UserMessage(GroupMessage):
    recipients = models.ManyToManyField(User, related_name='group_emails')

    group_message = models.OneToOneField(
        GroupMessage, on_delete=models.CASCADE, parent_link=True)

    @property
    def message_type(self):
        return MSG_TYPE_USER

    @staticmethod
    def create(subject, body, conference, objects_to):
        msg = UserMessage.objects.create(
            subject=subject, body=body, conference=conference)
        for user in objects_to:
            msg.recipients.add(user)
        msg.save()
        return msg

    def send(self, sender):
        # 1) Update status and save sender chair user:
        self.sent = False
        self.sent_by = sender
        self.save()

        # 2) For each user, we render this template with the given context,
        #    and then build the whole message by inserting this body into
        #    the frame. Plain-text version is also formed from HTML.
        frame = self.conference.email_settings.frame
        conference_context = get_conference_context(self.conference)
        for user in self.recipients.all():
            context = Context({
                **conference_context,
                **get_user_context(user, self.conference)
            }, autoescape=False)
            email = EmailMessage.create(
                group_message=self.group_message,
                user_to=user,
                context=context,
                frame=frame
            )
            email.send(sender)

        # 3) Update self status, write sending timestamp
        self.sent_at = timezone.now()
        self.sent = True
        self.save()
        return self


class SubmissionMessage(GroupMessage):
    recipients = models.ManyToManyField(
        Submission, related_name='group_emails')

    group_message = models.OneToOneField(
        GroupMessage, on_delete=models.CASCADE, parent_link=True)

    @property
    def message_type(self):
        return MSG_TYPE_SUBMISSION

    @staticmethod
    def create(subject, body, conference, objects_to):
        msg = SubmissionMessage.objects.create(
            subject=subject, body=body, conference=conference)
        for submission in objects_to:
            msg.recipients.add(submission)
        msg.save()
        return msg

    def send(self, sender):
        # 1) Update status and save sender chair user:
        self.sent = False
        self.sent_by = sender
        self.save()

        # 2) For each user, we render this template with the given context,
        #    and then build the whole message by inserting this body into
        #    the frame. Plain-text version is also formed from HTML.
        frame = self.conference.email_settings.frame
        conference_context = get_conference_context(self.conference)
        for submission in self.recipients.all():
            submission_context = get_submission_context(submission)
            for author in submission.authors.all():
                user = author.user
                context = Context({
                    **conference_context,
                    **submission_context,
                    **get_user_context(user, self.conference)
                }, autoescape=False)
                email = EmailMessage.create(
                    group_message=self.group_message,
                    user_to=user,
                    context=context,
                    frame=frame
                )
                email.send(sender)

        # 3) Update self status, write sending timestamp
        self.sent_at = timezone.now()
        self.sent = True
        self.save()
        return self


def get_group_message_model(msg_type):
    return {
        MSG_TYPE_USER: UserMessage,
        MSG_TYPE_SUBMISSION: SubmissionMessage,
    }[msg_type]


def get_message_leaf_model(msg):
    """If provided a `GroupMessage` instance, check the inheritance, find
    the most descent child and return it. Now the possible leaf models are
    `UserMessage` and `SubmissionMessage`."""
    if hasattr(msg, 'usermessage'):
        return msg.usermessage
    elif hasattr(msg, 'submissionmessage'):
        return msg.submissionmessage
    # Also check, maybe a message is already a leaf:
    if isinstance(msg, UserMessage) or isinstance(msg, SubmissionMessage):
        return msg
    # If neither succeeded, raise an error:
    raise TypeError(f'Not a group message: type(msg)')


class EmailMessage(models.Model):
    subject = models.TextField(max_length=1024)
    text_plain = models.TextField()
    text_html = models.TextField()
    user_to = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='emails'
    )
    sent_at = models.DateTimeField(auto_now_add=True)
    sent = models.BooleanField(default=False)
    sent_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL, null=True,
        related_name='sent_emails'
    )

    group_message = models.ForeignKey(
        GroupMessage,
        on_delete=models.SET_NULL,
        null=True,
        related_name='messages',
    )

    @staticmethod
    def create(group_message, user_to, context, frame):
        template_body = Template(group_message.body)
        template_subject = Template(group_message.subject)
        body_md = template_body.render(context)
        body_html = markdown(body_md)
        subject = template_subject.render(context)
        return EmailMessage.objects.create(
            user_to=user_to,
            group_message=group_message,
            subject=subject,
            text_html=frame.render_html(subject, body_html),
            text_plain=frame.render_plain(subject, body_md),
        )

    def send(self, sender):
        if not self.sent:
            from_email = settings.DEFAULT_FROM_EMAIL
            send_mail(self.subject, self.text_plain, from_email, [self.user_to],
                      html_message=self.text_html)
            self.sent_at = timezone.now()
            self.sent_by = sender
            self.sent = True
            self.save()
        return self


class SystemNotification(models.Model):
    """This model represents a system notification fired on a specific event.

    The model itself doesn't define the circumstances in which the message
    must be sent, which are subject to views.

    Notification is defined with a mandatory name, optional description,
    subject and template. If template is not assigned or subject is not
    specified, messages won't be sent.

    Notification can also be turned off with `is_active` flag field.
    """
    ASSIGN_STATUS_SUBMIT = 'assign_status_submit'
    ASSIGN_STATUS_REVIEW = 'assign_status_review'
    ASSIGN_STATUS_ACCEPT = 'assign_status_accept'
    ASSIGN_STATUS_REJECT = 'assign_status_reject'
    ASSIGN_STATUS_INPRINT = 'assign_status_inprint'
    ASSIGN_STATUS_PUBLISHED = 'assign_status_publish'

    NAME_CHOICES = (
        (ASSIGN_STATUS_REVIEW, 'Assign status REVIEW to the paper'),
        (ASSIGN_STATUS_SUBMIT, 'Assign status SUBMIT to the paper'),
        (ASSIGN_STATUS_ACCEPT, 'Assign status ACCEPT to the paper'),
        (ASSIGN_STATUS_REJECT, 'Assign status REJECT to the paper'),
        (ASSIGN_STATUS_INPRINT, 'Assign status IN-PRINT to the paper'),

wwwdccn/chair_mail/templates/chair_mail/_tab_nav.html
{###########################################################################}
{# Tab navigation for mail system.                                         #}
{#                                                                         #}
{# CONTEXT:                                                                #}
{# - `conference`                                                          #}
{# - `frame`: the default conference email frame template                  #}
{# - `active`: a string indicating which tab is currently active.          #}
{###########################################################################}
<ul class="nav nav-pills justify-content-start">
  <li class="nav-item">
    <a href="{% url 'chair_mail:overview' conf_pk=conference.pk %}"
       class="nav-link {% if active == 'overview' %}active{% endif %}">
      Overview
    </a>
  </li>
  <li class="nav-item">
    <a href="{% url 'chair_mail:frame-details' conf_pk=conference.pk %}"
       class="nav-link {% if active == 'frame' %}active{% endif %} {% if not frame %}disabled text-dark-2{% endif %}">
      Frame
    </a>
  </li>
  <li class="nav-item">
    <a href="{% url 'chair_mail:sent-messages' conf_pk=conference.pk %}"
       class="nav-link {% if active == 'messages' %}active{% endif %}">
      Messages
    </a>
  </li>
  <li class="nav-item">
    <a href="{% url 'chair_mail:notifications' conf_pk=conference.pk %}"
       class="nav-link {% if active == 'notifications' %}active{% endif %}">
      Notifications
    </a>
  </li>
</ul>

wwwdccn/chair_mail/templates/chair_mail/compose_to_single_user.html
{#-----------------------------------------------#}
{# CONTEXT:                                      #}
{# #}
{#-----------------------------------------------#}
{% extends "chair/base/_chair_overview_base.html" %}
{% load bootstrap4 %}
{% load submission_extras %}

{% block title %}
  Compose message
{% endblock %}

{% block header %}
  {% include 'user_site/components/navigation.html' with active='' %}
{% endblock %}

{% block css %}
<link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<style>
#message-editor .ql-editor {
  padding: 12px 15px !important;
}
</style>
{% endblock %}

{% block viewPanelTitle %}
Compose message to {{ member.profile.get_full_name }}
{% endblock %}

{% block viewPanelBody %}
<div class="container my-3">

  <form action="{% url 'chair_mail:compose-user' conf_pk=conference.pk user_pk=member.pk %}"
        id="newMessageForm" method="POST">

    {% csrf_token %}

    <input type="hidden" name="next" id="id_next" value="{{ next }}">

    <div class="form-group row">
      <div class="col-sm-10 col-md-11">
        {% bootstrap_field form.subject show_label=False %}
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10 col-md-11">
        <textarea name="text_html" id="id_text_html" cols="3" rows="1" class="form-control" hidden></textarea>
        <textarea name="text_plain" id="id_text_plain" cols="3" rows="1" class="form-control" hidden></textarea>

        <div id="message">
          <div id="message-toolbar">
            <span class="ql-formats">
              <select class="ql-font"></select>
              <select class="ql-size">
                <option value="0.8em">Small</option>
                <option value="1em">Normal</option>
                <option value="2em">Large</option>
                <option value="3em">Huge</option>
              </select>
            </span>
            <span class="ql-formats">
              <button class="ql-bold"></button>
              <button class="ql-italic"></button>
              <button class="ql-underline"></button>
              <button class="ql-strike"></button>
            </span>
            <span class="ql-formats">
              <select class="ql-color"></select>
              <select class="ql-background"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-script" value="sub"></button>
              <button class="ql-script" value="super"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-header" value="1"></button>
              <button class="ql-header" value="2"></button>
              <button class="ql-blockquote"></button>
              <button class="ql-code-block"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-list" value="ordered"></button>
              <button class="ql-list" value="bullet"></button>
            </span>
            <span class="ql-formats">
              <select class="ql-align"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-link"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-clean"></button>
            </span>
          </div>
          <div id="message-editor" style="position: relative; height: 350px;"></div>
        </div>

        <small class="form-text text-muted">
          {% include 'chair_mail/components/message_to_user_help.html' %}
        </small>
      </div>
    </div>
    <div class="form-group d-flex">
      <button type="submit" class="btn btn-primary" id="sendMessageButton">Send message</button>
      <a href="{{ next }}" class="btn btn-outline-secondary ml-auto">Cancel</a>
    </div>
  </form>
</div>
{% endblock %}

{% block script %}
<script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
<script>
$(document).ready(function () {
  let AlignStyle = Quill.import('attributors/style/align');
  Quill.register(AlignStyle, true);

  let BackgroundStyle = Quill.import('attributors/style/background');
  Quill.register(BackgroundStyle, true);

  let ColorStyle = Quill.import('attributors/style/color');
  Quill.register(ColorStyle, true);

  let FontStyle = Quill.import('attributors/style/font');
  Quill.register(FontStyle, true);

  let SizeStyle = Quill.import('attributors/style/size');
  SizeStyle.whitelist = ['0.8em', '1em', '2em', '3em'];
  Quill.register(SizeStyle, true);

  const quill = new Quill('#message-editor', {
    theme: 'snow',
    modules: {
      'toolbar': '#message-toolbar',
    },
    placeholder: "Compose a letter...",
  });

  $('#newMessageForm').on('submit', function () {
    const editor = $('#message-editor .ql-editor');
    const htmlTextArea = $('#id_text_html');
    const plainTextArea = $('#id_text_plain');
    const plainText = quill.getText();
    const htmlValue = editor.html();
    htmlTextArea.text(htmlValue);
    plainTextArea.text(plainText);
    if (plainText.trim() === "") {
      return confirm('Are you sure you want to send empty message?');
    }
    return true;
  });
});
</script>
{% endblock %}

wwwdccn/chair_mail/templates/chair_mail/compose_user.html
{#-----------------------------------------------#}
{# CONTEXT:                                      #}
{# #}
{#-----------------------------------------------#}
{% extends "chair/base/_chair_preview_base.html" %}
{% load bootstrap4 %}
{% load submission_extras %}

{% block title %}
  Compose message
{% endblock %}

{% block header %}
  {% include 'user_site/components/navigation.html' with active='' %}
{% endblock %}

{% block css %}
<link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<style>
#message-editor .ql-editor {
  padding: 12px 15px !important;
}
</style>
{% endblock %}

{% block viewPanelTitle %}
Compose message to {{ member.profile.get_full_name }}
{% endblock %}

{% block viewPanelBody %}
<div class="container my-3">

  <form action="{% url 'chair_mail:compose-user' conf_pk=conference.pk user_pk=member.pk %}"
        id="newMessageForm" method="POST">

    {% csrf_token %}

    <input type="hidden" name="next" id="id_next" value="{{ next }}">

    <div class="form-group row">
      <div class="col-sm-10 col-md-11">
        {% bootstrap_field form.subject show_label=False %}
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10 col-md-11">
        <textarea name="body_html" id="id_body_html" cols="3" rows="1" class="form-control" hidden></textarea>
        <textarea name="body_plain" id="id_body_plain" cols="3" rows="1" class="form-control" hidden></textarea>

        <div id="message">
          <div id="message-toolbar">
            <span class="ql-formats">
              <select class="ql-font"></select>
              <select class="ql-size">
                <option value="0.8em">Small</option>
                <option value="1em">Normal</option>
                <option value="2em">Large</option>
                <option value="3em">Huge</option>
              </select>
            </span>
            <span class="ql-formats">
              <button class="ql-bold"></button>
              <button class="ql-italic"></button>
              <button class="ql-underline"></button>
              <button class="ql-strike"></button>
            </span>
            <span class="ql-formats">
              <select class="ql-color"></select>
              <select class="ql-background"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-script" value="sub"></button>
              <button class="ql-script" value="super"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-header" value="1"></button>
              <button class="ql-header" value="2"></button>
              <button class="ql-blockquote"></button>
              <button class="ql-code-block"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-list" value="ordered"></button>
              <button class="ql-list" value="bullet"></button>
            </span>
            <span class="ql-formats">
              <select class="ql-align"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-link"></button>
            </span>
            <span class="ql-formats">
              <button class="ql-clean"></button>
            </span>
          </div>
          <div id="message-editor" style="position: relative; height: 350px;"></div>
        </div>

        <small class="form-text text-muted">
          {% include 'chair_mail/components/message_to_user_help.html' %}
        </small>
      </div>
    </div>
    <div class="form-group d-flex">
      <button type="submit" class="btn btn-primary" id="sendMessageButton">Send message</button>
      <a href="{{ next }}" class="btn btn-outline-secondary ml-auto">Cancel</a>
    </div>
  </form>
</div>
{% endblock %}

{% block script %}
<script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
<script>
$(document).ready(function () {
  let AlignStyle = Quill.import('attributors/style/align');
  Quill.register(AlignStyle, true);

  let BackgroundStyle = Quill.import('attributors/style/background');
  Quill.register(BackgroundStyle, true);

  let ColorStyle = Quill.import('attributors/style/color');
  Quill.register(ColorStyle, true);

  let FontStyle = Quill.import('attributors/style/font');
  Quill.register(FontStyle, true);

  let SizeStyle = Quill.import('attributors/style/size');
  SizeStyle.whitelist = ['0.8em', '1em', '2em', '3em'];
  Quill.register(SizeStyle, true);

  const quill = new Quill('#message-editor', {
    theme: 'snow',
    modules: {
      'toolbar': '#message-toolbar',
    },
    placeholder: "Compose a letter...",
  });

  $('#newMessageForm').on('submit', function () {
    const editor = $('#message-editor .ql-editor');
    const htmlTextArea = $('#id_body_html');
    const plainTextArea = $('#id_body_plain');
    const plainText = quill.getText();
    const htmlValue = editor.html();
    htmlTextArea.text(htmlValue);
    plainTextArea.text(plainText);
    if (plainText.trim() === "") {
      return confirm('Are you sure you want to send empty message?');
    }
    return true;
  });
});
</script>
{% endblock %}

wwwdccn/chair_mail/templates/chair_mail/sent_messages_list.html
{###########################################################################}
{# List of sent emails.                                                    #}
{#                                                                         #}
{# CONTEXT:                                                                #}
{# - `email_messages`: sequence of email messages.                         #}
{#                                                                         #}
{# INHERITED CONTEXT:                                                      #}
{# - `conference`                                                          #}
{# - `active_tab`: value of `active` context variable for tab navigation   #}
{# - `template`: the default conference email template                     #}
{###########################################################################}
{% extends 'chair_mail/_base.html' %}
{% load static %}

{% block tabViewContent %}
  <div class="container">
    <div class="list-group">
      {% for msg in email_messages %}
        <a class="d-flex list-group-item list-group-item-action py-1"
           href="{% url 'chair_mail:message-details' conf_pk=conference.pk msg_pk=msg.pk %}?next={{ request.get_full_path|urlencode }}">
          <div>
            <span class="dccn-text-small text-muted mr-2">{{ msg.sent_at|date:"d.m.Y G:i" }}</span>
            <span class="dccn-text-0 font-weight-bold">{{ msg.subject }}</span>
          </div>
          <div class="ml-auto"><span class="badge badge-info">{{ msg.message_type }}</span></div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}