wwwdccn/chair/urls.py
from django.urls import path

from chair.views import export
from .views import dashboard, submissions, users


app_name = 'chair'

urlpatterns = [
    path('<int:conf_pk>/', dashboard.overview, name='home'),

    #
    # Submissions
    #
    path('<int:conf_pk>/submissions/', submissions.list_submissions, name='submissions'),
    path('<int:conf_pk>/submissions/create/', submissions.create_submission, name='submission-create'),
    path('<int:conf_pk>/submissions/compose_redirect/', submissions.compose_redirect, name='submissions-compose-redirect'),
    path('submissions/<int:sub_pk>/feed_item/', submissions.feed_item, name='submission-feed-item'),
    path('submissions/<int:sub_pk>/overview/', submissions.overview, name='submission-overview'),
    path('submissions/<int:sub_pk>/metadata/', submissions.metadata, name='submission-metadata'),
    path('submissions/<int:sub_pk>/authors/', submissions.authors, name='submission-authors'),
    path('submissions/<int:sub_pk>/authors/delete/', submissions.delete_author, name='submission-author-delete'),
    path('submissions/<int:sub_pk>/authors/create/', submissions.create_author, name='submission-author-create'),
    path('submissions/<int:sub_pk>/authors/invite/', submissions.invite_author, name='submission-author-invite'),
    path('submissions/<int:sub_pk>/authors/reorder/', submissions.reorder_authors, name='submission-authors-reorder'),
    path('submissions/<int:sub_pk>/rev_man/', submissions.review_manuscript, name='submission-review-manuscript'),
    path('submissions/<int:sub_pk>/rev_man/delete/', submissions.delete_review_manuscript, name='submission-review-manuscript-delete'),
    path('submissions/<int:sub_pk>/revoke_review/', submissions.revoke_review, name='revoke-review'),
    path('submissions/<int:sub_pk>/reviews/', submissions.reviews, name='submission-reviewers'),
    path('submissions/<int:sub_pk>/messages/', submissions.emails, name='submission-messages'),
    path('submissions/<int:sub_pk>/camera_ready/', submissions.camera_ready, name='submission-camera-ready'),
    path('submissions/<int:sub_pk>/reviews/assign/', submissions.assign_reviewer, name='assign-reviewer'),
    path('submissions/<int:sub_pk>/reviews/<int:rev_pk>/delete/', submissions.delete_review, name='delete-review'),
    path('submissions/<int:sub_pk>/delete/', submissions.delete_submission, name='submission-delete'),
    path('attachments/<int:att_pk>/download/', submissions.download_attachment, name='download-attachment'),

    #
    # Users
    #
    path('<int:conf_pk>/users/', users.list_users, name='users'),
    path('<int:conf_pk>/users/compose_redirect/', users.compose_redirect, name='users-compose-redirect'),
    path('<int:conf_pk>/users/<int:user_pk>/feed_item/', users.feed_item, name='user-feed-item'),
    path('<int:conf_pk>/users/<int:user_pk>/overview/', users.overview, name='user-overview'),
    path('<int:conf_pk>/users/<int:user_pk>/messages/', users.emails, name='user-messages'),
    path('<int:conf_pk>/users/export/csv/', users.export_csv, name='users-export-csv'),

    #
    # Exports
    #
    path('<int:conf_pk>/export/submissions/', export.export_submissions, name='export-submissions'),
    path('<int:conf_pk>/export/reviews_doc/', export.export_reviews_doc, name='export-reviews-doc'),
]

wwwdccn/conferences/urls.py
from django.urls import path

from . import views


app_name = 'conferences'
urlpatterns = [
    path('ajax/<int:pk>/', views.ajax_details),
    path('ajax/stype/<int:pk>/', views.ajax_stype_details),

    path('', views.conferences_list,
         name='list'),
    path('new/', views.conference_create, name='create'),
    path('<int:pk>/', views.conference_details, name='details'),
    path('<int:pk>/settings/', views.conference_edit, name='edit'),
    path('<int:pk>/stages/submission', views.conference_submission_stage,
         name='submission-deadline'),
    path('<int:pk>/stages/reviews', views.conference_review_stage,
         name='review-deadline'),
    path('<int:pk>/proceedings/new/', views.proceedings_create,
         name='proceedings-create'),
    path('<int:pk>/proceedings/<int:proc_pk>/', views.proceeding_type_details,
         name='proceedings-update'),
    path('<int:pk>/proceedings/<int:proc_pk>/delete/', views.proceedings_delete,
         name='proceedings-delete'),
    path('<int:pk>/stype/new/', views.submission_type_create,
         name='stype-create'),
    path('<int:pk>/stype/<int:sub_pk>/', views.submission_type_update,
         name='stype-update'),
    path('<int:pk>/stype/<int:sub_pk>/delete/', views.submission_type_delete,
         name='stype-delete'),
    path('<int:pk>/topics/', views.topics_list, name='topics'),
    path('<int:pk>/topics/<int:topic_pk>/delete/', views.topic_delete,
         name='topic-delete'),
    path('<int:pk>/topics/<int:topic_pk>/', views.topic_update,
         name='topic-update'),
    path('<int:pk>/topics/reorder/', views.topics_reorder,
         name='topics-reorder'),
    path('<int:pk>/proceedings/<int:proc_pk>/volumes/new/',
         views.proceeding_volume_create, name='volume-create'),
    path('<int:pk>/proceedings/volumes/<int:vol_pk>/delete/',
         views.proceeding_volume_delete, name='volume-delete'),
    path('<int:pk>/proceedings/volumes/<int:vol_pk>/',
         views.proceeding_volume_details, name='volume-details'),
    path('<int:pk>/proceedings/<int:proc_pk>/artifacts/new/',
         views.artifact_create, name='artifact-create'),
    path('<int:pk>/proceedings/artifacts/<int:art_pk>/delete/',
         views.artifact_delete, name='artifact-delete'),
    path('<int:pk>/proceedings/artifacts/<int:art_pk>/',
         views.artifact_details, name='artifact-details'),
    path('<int:pk>/proceedings/artifacts/<int:art_pk>/toggle_editable/',
         views.artifact_toggle_editable, name='artifact-toggle-editable'),
    path('<int:pk>/proceedings/artifacts/links/<int:link_id>/',
         views.descriptor_link_details, name='descriptor-link-details'),
    path('<int:pk>/proceedings/artifacts/<int:art_pk>/links/create',
         views.descriptor_link_create, name='descriptor-link-create'),
    path('<int:pk>/proceedings/artifacts/links/<int:link_id>/delete/',
         views.descriptor_link_delete, name='descriptor-link-delete'),
]

wwwdccn/review/urls.py
from django.urls import path

from . import views


app_name = 'review'

urlpatterns = [
    path('<int:pk>/', views.review_details, name='review-details'),
    path('<int:pk>/refuse/', views.decline_review, name='review-decline'),
    # API:
    path('api/<int:sub_id>/decision/update/', views.update_decision, name='update-decision'),
    path('api/<int:conf_pk>/users/<int:user_pk>/make_reviewer/', views.create_reviewer, name='make-reviewer'),
    path('api/<int:conf_pk>/users/<int:user_pk>/revoke_reviewer/', views.revoke_reviewer, name='revoke-reviewer'),
]

wwwdccn/user_site/urls.py
from django.urls import path

from . import views


app_name = 'user_site'

urlpatterns = [
    path('submissions/', views.submissions_list, name='submissions'),
    path('reviews/', views.reviews_list, name='reviews'),
]

wwwdccn/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('search/', views.search_users, name='search'),
    path('profile/overview/', views.profile_overview, name='profile-overview'),
    path('profile/account/', views.profile_account, name='profile-account'),
    path('profile/personal/', views.profile_personal, name='profile-personal'),
    path('profile/professional/', views.profile_professional,
         name='profile-professional'),
    path('profile/reviewer/', views.profile_reviewer, name='profile-reviewer'),
    path('email/update/', views.update_email, name='update-email'),
    path('subscriptions/update/', views.update_subscriptions,
         name='update-subscriptions'),
    path('password/update/', views.update_password, name='update-password'),
    path('avatar/update/', views.update_avatar, name='update-avatar'),
    path('avatar/delete/', views.delete_avatar, name='delete-avatar'),
    path('delete/', views.delete_account, name='delete'),
]

wwwdccn/wwwdccn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('public_site.urls')),
    path('user/', include('user_site.urls')),
    path('auth/', include('auth_app.urls')),
    path('users/', include('users.urls')),
    path('registration/', include('registration.urls')),
    path('conferences/', include('conferences.urls')),
    path('submissions/', include('submissions.urls')),
    path('chair/', include('chair.urls')),
    path('chair_mail/', include('chair_mail.urls')),
    path('review/', include('review.urls')),
    path('gears/', include('gears.urls')),
    path('proceedings/', include('proceedings.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.USE_LOCAL_MEDIA:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

wwwdccn/user_site/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from review.models import Review
from submissions.models import Submission


@login_required
def submissions_list(request):
    return render(request, 'user_site/submissions.html', {
        'submissions': Submission.objects.filter(authors__user=request.user),
    })


@login_required
def reviews_list(request):
    submissions = Submission.objects.filter(authors__user=request.user)
    return render(request, 'user_site/reviews.html', {
        'numSubmissions': len(submissions),
        'reviews': Review.objects.filter(reviewer__user=request.user),
    })

wwwdccn/user_site/views/submissions.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from submissions.models import Submission


@login_required
def user_details(request):
    return render(request, 'user_site/submissions.html', {
        'submissions': Submission.objects.filter(authors__user=request.user)
    })

wwwdccn/user_site/templates/user_site/components/navigation.html
{# ==================================================#}
{# CONTEXT:                                          #}
{#                                                   #}
{# * active: 'submissions', 'reviews', 'conferences' #}
{# ==================================================#}
{% load review_extras %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="{% url 'user_site:submissions' %}" class="nav-link {% if active == 'submissions' %}active{% endif %}">
          {% if active == 'submissions' %}<span class="text-secondary">|</span>{% endif %} Submissions
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'user_site:reviews' %}" class="nav-link {% if active == 'reviews' %}active{% endif %}">
          {% if active == 'reviews' %}<span class="text-secondary">|</span>{% endif %} Reviews
          {% if user|is_reviewer %} <span class="badge badge-light">{{ user|count_incomplete_reviews }}</span>{% endif %}
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'conferences:list' %}" class="nav-link {% if active == 'conferences' %}active{% endif %}">
          {% if active == 'conferences' %}<span class="text-secondary">|</span>{% endif %} Conferences
        </a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" id="userMenuDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.profile.first_name }} {% if user.profile.avatar %}<img src="{{ user.profile.avatar.url }}" alt="" class="img-fluid rounded-circle" width="24" height="24">{% endif %}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenuDropdown">
          <a href="{% url 'users:profile-overview' %}" class="dropdown-item">Profile</a>
          <a href="{% url 'logout' %}" class="dropdown-item">Sign out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

wwwdccn/user_site/templates/user_site/components/profile_panel.html
{# ==================================================#}
{# CONTEXT:                                          #}
{#                                                   #}
{# * user                                            #}
{# * numSubmissions                                  #}
{# * numReviews                                      #}
{# ==================================================#}
<div class="dccn-panel dccn-panel-user">
  <img src="{{ user.profile.avatar.url }}" alt="avatar" class="mt-3 align-self-center d-block mr-3 mx-lg-auto rounded-circle" style="width: 120px;">
  <ul class="list-unstyled">
    <li class="dccn-title">{{ user.profile.get_full_name }}</li>
    <li class="dccn-text">{{ user.profile.affiliation }}</li>
    <li class="dccn-text">{{ user.profile.role }}{% if user.profile.role != "" and user.profile.degree != "" %},{% endif %} {{ user.profile.degree }}</li>
    <li class="dccn-text mt-2"><a href="{% url 'users:profile-overview' %}" class="dccn-link">Edit Profile...</a></li>
  </ul>
  <hr class="d-none d-lg-block">
  <ul class="list-unstyled mt-lg-1 ml-auto ml-lg-0">
    <li class="dccn-text-normal">
      <span class="dccn-text-large-light">{{ numSubmissions }}</span> <a href="{% url 'user_site:submissions' %}" class="dccn-link">submission{{ numSubmissions|pluralize:',s' }}</a>
    </li>
    <li class="dccn-text-normal">
      <span class="dccn-text-large-light">{{ numReviews }}</span> <a href="{% url 'user_site:reviews' %}" class="dccn-link">incomplete review{{ numReviews|pluralize:',s' }}</a>
    </li>
  </ul>
</div>

wwwdccn/user_site/templates/user_site/components/review_card.html
{###################}
{# CONTEXT:        #}
{# * review        #}
{###################}
<div class="dccn-feed-item">
  <div class="dccn-feed-item-top">
    <div class="dccn-feed-item-label dccn-feed-item-conf">{{ review.paper.conference.short_name }}</div>
    <div class="dccn-feed-item-label ml-auto mr-3" data-toggle="tooltip" title="End of review">
      <i class="far fa-clock"></i> <span class="font-weight-lighter">{{ review.paper.conference.review_stage.end_date }}</span>
    </div>
    <div class="dccn-feed-item-label dccn-feed-item-status">
      <i class="fas fa-circle {% if review.submitted %}text-success{% else %}text-warning{% endif %}"></i>
    </div>
  </div>
  <p class="dccn-feed-item-title">
    <a href="{% url 'review:review-details' pk=review.pk %}">
      {{ review.paper.title }}
    </a>
  </p>
  <div class="dccn-feed-item-messages">
    {% for warning in review.warnings %}
      <div class="dccn-feed-item-row">
        <div class="dccn-feed-item-message-text">
          <i class="fas fa-exclamation-triangle text-warning"></i> {{ warning }}
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="dccn-feed-item-footer">
    <a href="{% url 'review:review-details' pk=review.pk %}" class="dccn-feed-item-link"><i class="far fa-edit"></i> Edit</a>
    <div class="dccn-feed-item-id ml-auto">#{{ review.pk }}</div>
  </div>
</div>